print("welcome to warriors world hunting traning")
print("wich cat do you want to use hawkpelt, fluffyfur, firestar, softpelt, cloudtail,")
cat = input()
print('ok lets go get', cat)
h = input()
print("ok we are at the hunting grounds type yes i do see some mice")
ab = input()
print("you are right i", ab)
print("prey")
print("ok lets go catch it")
zxyuyfdehufhfeuyhydhsrfhgas = input()
print("good job catching it")
print("ok now should we eat that nice big mouse type if yes type yes we should if no type no we should not")
c = input()
print("i agree ", c)
print("eat it")
print("game finishd")
cat = open('README.md', 'w')
cat.write('README now!')
